flyway:
  enabled: true
  locations: classpath:db/migration
  schemas: [finance]

spring:

  datasource:
    url: jdbc:h2:mem:finance
    password: postgres
    username: postgres

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      show_sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true

logging:

  file: logs/application-debug.log

  level:
    root: ERROR
    org.springframework.web: ERROR
    com.silionie: ERROR
    org.hibernate: ERROR

server:
  port: 8080